name: rag
channels:
- defaults
- conda-forge
dependencies:
- python=3.10
- pip
- pip:
- fastapi==0.115.0
- uvicorn[standard]==0.30.6
- python-dotenv==1.0.1
- pymupdf==1.24.9
- pillow==10.4.0
- ftfy==6.2.0
- rapidfuzz==3.8.1
- paddleocr==2.9.1
- langchain==0.2.14
- langchain-community==0.2.12
- langgraph==0.2.29
- faiss-cpu==1.8.0.post1
- langchain-google-genai==2.0.3
- jinja2==3.1.4
- requests==2.32.3
- python-docx==1.1.2